#!/bin/bash

rm /etc/nginx/sites-available/*
rm /etc/nginx/sites-enabled/*

cp etc/nginx/sites-available/* /etc/nginx/sites-available
ln -s /etc/nginx/sites-available/* /etc/nginx/sites-enabled/*

service nginx reload
